name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: node
    steps:  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
      - name: Build the package
        run: npm run build
