name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:  
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: IgnusG/jest-report-action@v2.3.3
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci
      - name: Build the package
        run: npm run build:ci
